### ISSUE TITLE
Whole project re-planning

### ISSUE THREAD

**Issue by leandrosardi** [FreeLeadsData/docs#17]
## Problem

These are the problems I found when trying to sell **FreeLeadsData**:

1. Clients like the product, but it is not something they need right now.
2. It is hard to find a LARGE list of leads who need this service right now.
3. Even clients who are actively looking for a scraping service, have no idea how to run a cold cammpaign properly.
4. And clients who are skilled use to have many providers and it is very hard to negotiate with them.
5. Clients don't use to stick a monthly fee. Instead they want to pay on demand, or pay LTDs.
6. Many clients came with SPECIFIC requirements that requires CUSTOM DEVELOPMENT (eg: scraping social profiles, scraping other providers, other websites)

## Solutions

1. Run Cold Email Campaign experiments using our current software as is, and sell seminars + software with a monthly fee. --> 🆗 

2. Run MASSIVE campaigns again and again, offering different products. --> :ok:  

4. Develop custom scraping software projects + a monthly fee for running scrapers. --> ⛔ 

5. Get back to run an agency. --> ⛔

**Comment by leandrosardi** [comment]
Done.

**Comment by C-Nubela** [comment]
Leandro,

I work at Proxycurl.com, I'm a bit curious, who are you using to scrape your data?

Also, in terms of cold emailing and AI generation, [we published this article right here](https://nubela.co/blog/how-salesforge-integrates-rich-prospecting-data-with-chatgpt-to-automatically-personalize-emails/?utm_campaign=content_amplification&utm_source=reddit&utm_medium=social&utm_content=comments) that you might find value out of (we interviewed Salesforge).

**Comment by C-Nubela** [comment]
> > Leandro,
> > I work at Proxycurl.com, I'm a bit curious, who are you using to scrape your data?
> > Also, in terms of cold emailing and AI generation, [we published this article right here](https://nubela.co/blog/how-salesforge-integrates-rich-prospecting-data-with-chatgpt-to-automatically-personalize-emails/?utm_campaign=content_amplification&utm_source=reddit&utm_medium=social&utm_content=comments) that you might find value out of (we interviewed Salesforge).
> 
> Good outreach strategy man.
> 
> I think you are not interested on how I am scraping data, but you are trying to drive traffic to your link instead. Am I right?

Haha, thanks! To answer your question: both. 

By the way, I actually did make an account on FreeLeadsData. It's interesting project.

We would be happy to help you out -- for example, we do provide a free [Disposable Email Check Endpoint](https://nubela.co/proxycurl/docs#contact-api-disposable-email-address-check-endpoint) that could be useful.

**Comment by leandrosardi** [comment]
## New Marketing Plan (draft)

MARKETING PLAN - STAGE 1: Direct 1-to-1 Sales

Setting Up CS Platform.
Setting Up Domain for Transactional Emails to FreeLeadsData users. 
Setting Up Domain for Marketing Emails to FreeLeadsData users.

Setting Up Email FollowUp series to FreeLeadsData leads.
Setting Up Email FollowUp series to FreeLeadsData clients.

Setting Up Facebook Accounts
Setting Up LinkedIn Accounts
Setting Up Cold Email Domains

Daily Task: Announcing Beta-Test in Facebook Groups
Daily Task: Facebook DMs for inviting to Beta-Test
Daily Task: LinkedIn DMs for inviting to Beta-Test
Daily Task: Cold Emails to FLD records inviting to Beta-Test

Goals: 3 Clients/Week (from $47 to $197 MRR), Scale Clients Base, Outsource Sales 

MARKETING PLAN - STATE 2: SellDaddy

Develop Website
Develop First Month Content
Develop Direct 1-to-1 Sales
Develop SoloAds Strategy

MARKETING PLAN - STAGE 3: Authority

Running experiments to build case of studies for our content marketing.
Content Marketing: Facebook Groups, BHW, 
YouTube Content
Freelancing Platforms: Fiverr, UpWork, etc.

MARKETING PLAN - STAGE 4: Traffic

Software Directories
LTD Marketplaces
Facebook Re-Targeting
Google Re-Targeting
Instagram Re-Targeting
